apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: development
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db.name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: username
